name: bacon-ipsum
version: 0.1
summary: Bacon Ipsum
description: Making your text full of bacon-y goodness
architectures: ["all"]

parts:
  bacon:
    plugin: copy
    files:
      bacon-ipsum-logo.svg: bacon-ipsum-logo.svg
      bacon-ipsum-pig.png: bacon-ipsum-pig.png
      bacon-ipsum.qml: bacon-ipsum.qml

apps:
  bacon:
    command: qmlscene bacon-ipsum.qml
    plugs: ["unity8", "network-client"]

