name: bacon-ipsum
version: 0.1
summary: Bacon Ipsum
description: Making your text full of bacon-y goodness
architectures: ["all"]

parts:
  bacon:
    plugin: copy
    files:
      bacon-ipsum-logo.svg: bacon-ipsum-logo.svg
      bacon-ipsum-pig.png: bacon-ipsum-pig.png
      bacon-ipsum.qml: bacon-ipsum.qml
      bacon-ipsum.sh: bacon-ipsum.sh
    after: ["desktop/qt5"]
    stage-packages:
      - qmlscene
      - qml-module-ubuntu-components
      - qtdeclarative5-ubuntu-content1

apps:
  bacon-ipsum:
    command: desktop-launch $SNAP/bacon-ipsum.sh
    plugs: ["unity7", "network-client"]

